#ifndef STUN_ERROR_CODES_H
#define STUN_ERROR_CODES_H

namespace Stun
{
#define SMEC_CLASS 0
  typedef enum StunMessageErrorCodes
  {
    SMEC_SUCCESS = SMEC_CLASS + 0,
    SMEC_READ_ERROR = SMEC_CLASS + 1,
    SMEC_WRITE_ERROR = SMEC_CLASS + 2,
    SMEC_NOT_STUN_MSG_ERROR = SMEC_CLASS + 4,
    SMEC_TOO_MANY_ATTRIBUTES = SMEC_CLASS + 5,
    SMEC_ATTRIBUTE_NOT_FOUND = SMEC_CLASS + 6
  }StunMessageErrorCodes;

#define AEC_CLASS 100
  typedef enum AttributeErrorCodes
  {
    AEC_SUCCESS = AEC_CLASS + 0,
    AEC_READING_ERROR = AEC_CLASS + 1,
    AEC_WRITING_ERROR = AEC_CLASS + 2,
    AEC_CONVERTION_ERROR = AEC_CLASS + 3,
    AEC_ENCRYPTION_ERROR = AEC_CLASS + 4,
    AEC_DECRYPTION_ERROR = AEC_CLASS + 5,
    AEC_NO_SUCH_READING_FUNCTION = AEC_CLASS + 6,
    AEC_NO_SUCH_WRITING_FUNCTION = AEC_CLASS + 7,
    AEC_NOT_SUPPORTED_FUNCTION = AEC_CLASS + 8
  }AttributeErrorCodes;

}

#endif
